#          -> couch_peruser / enable: true
#                             delete_dbs: true
#          -> chttpd / admin_only_all_dbs  :  false
#          -> chttpd_auth / users_db_public: true
#          -> public_fields: _id, name, type, role
#          -> couchdb / max_document_size: 20000000

[log]
#level = debug
level = info

[couchdb]
single_node=true
max_document_size = 20000000

[couch_peruser]
enable = true
delete_dbs = true

[chttpd]
# false ist der default wert:
#admin_only_all_dbs = true

[admins]
admin = -pbkdf2:sha256-ffd1c0efe017558e4dd94460a03bbbb3a0a0957d051ca9925a292f36c7cd0a92,5b7e31778d63a8fa27c47aaa1d2d8963,600000

[couchdb]
uuid = ba9bc05d7a11013bbd0712856a7d6726

[chttpd_auth]
secret = b313b067703a06a9b14fcf36e843a6b3
users_db_public=true
public_fields=_id, name, type, role
